### PR TITLE
Cocoapods support swift 5

### PR DESCRIPTION
**Pull request by hoangtuanfithou**
This is not a real PR.

@RonanMcH and Zendesk team !

Do you guys have any plan about supporting Xcode 11 ?
We are using Zendesk SDK and can not build with Xcode 11.

Thank you

### CODE REVIEW

**Comment by baz8080** [comment]
It is on the way, see https://develop.zendesk.com/hc/en-us/articles/360025263473  for our policy.

**Comment by hoangtuanfithou** [comment]
@baz8080 ok, thank you, looking forward to beta build of zendesk asap, cause without it we can not test our project on iOS 13, Xcode 11.
Thank you.

**Comment by jklausa** [comment]
Y'all have any updates on this? It's been over a month.

**Comment by designsimply** [comment]
👋 I am also looking for an update on when we can expect to have a Zendesk SDK beta version for iOS 13 testing.

Jotting down some notes for reference, https://develop.zendesk.com/hc/en-us/articles/360025263473 says

<blockquote>When a beta version is released by Apple, Zendesk attempts to build the SDKs with the “Beta n” version:

* If the build passes, we run our automated test suites on it and release it. Normally a production release would involve more testing, including manual tests, but this would delay delivering the Beta build.
* If the build fails, we attempt to debug any issues though we can’t guarantee that we'll have a build for that beta. In the past, we faced some bugs from Apple on beta releases which prevented us from compiling for that specific version. The problem was usually solved in one of the following versions.</blockquote>

Here is Apple's iOS 13 timeline so far from what I can see:

* 2019-06-03 - first iOS 13 beta released to to registered developers. ([ref](https://en.wikipedia.org/wiki/IOS_13#Introduction_and_initial_release))
* 2019-06-18 - second iOS 13 beta released to to registered developers.
* 2019-06-24 - first public beta of iOS 13 released.
* 2019-07-29 - iOS 13 beta 5 released. ([ref](https://developer.apple.com/news/releases/?id=07292019c))

**Pull request closed without merging**
