### PR TITLE
fix typo in protocol name

### PR DESCRIPTION
**Pull request by rockshassa**
LMFTFY

### CODE REVIEW

**Comment by baz8080** [comment]
@rockshassa thanks for pointing this out. I've made an issue for it here: https://github.com/zendesk/zendesk_sdk_ios/issues/109

We usually fix these on our end and then push them from there to here when we release.

**Comment by baz8080** [comment]
@rockshassa We've made this fix internally. I'm going to close this PR, you should see the fix in the next version.

**Comment by rockshassa** [comment]
thanks @baz8080 !
random unrelated question, 
does `ZDKHelpCenter presentHelpCenterWithNavController:` (and similar) really need to accept a UINavigationController? If I pass in a UIViewController instead, will things break? It seems to work for me locally, and the comments suggest UIViewController is sufficient.

**Comment by StevenDiviney** [comment]
@rockshassa Using a UIViewController is fine for presentHelpCenterWithNavController, that method calls presentViewController on the controller passed in. presentViewController is a UIViewContoller method, inherited by UINavigationController, so everything works you will just get a type warning.

We wrap the presenting with presentHelpCenterWithNavController etc. so we can do some intermediary stuff, none of which is dependent on a UINavigationController. We may ditch this in the future.

**Comment by rockshassa** [comment]
Awesome, thanks for the info!

**Pull request closed without merging**
