### PR TITLE
Removing 4.1 support

### PR DESCRIPTION
**Pull request by divo**
Deleting 2.0.1

### CODE REVIEW

**Comment by dcvz** [comment]
Why was this removed?

**Comment by divo** [comment]
@dcvz because a bug in the Swift optimizer is causing the SDK to crash. We are working on a fix

**Comment by dcvz** [comment]
Thanks for the reply @divo. Any estimate? At the moment I can't include the Zendesk framework into our project because the current frameworks are compiled for a different Swift version. Or is there a Swift 3.3 version somewhere?

**Comment by divo** [comment]
Swift 3.3 is a compatibility mode for 4.1, so unfortunately not. We should have a release out this week but it may have to be pushed back to next week.

**Comment by divo** [comment]
@dcvz We have release 2.0.2 with 4.1 support

**Pull request merged**
