### PR TITLE
Release of Zendesk SDK 3.0.2 built with swift 5.1

### PR DESCRIPTION
**Pull request by HamstringAssassin**

### CODE REVIEW

**Comment by foxware00** [comment]
@ronan-mch any word on 5.1.1 support. Unable to build project with the latest stable XCode

**Comment by H3ndrx** [comment]
This sdk is a joke... Each time swift compiler is updated Zendesk SDK is not compiling... great job guys! 👌🏼🤔

**Comment by foxware00** [comment]
@bielikb @RonanMcH Can we get an update on this. It's incredibly annoying not having a build supported by the latest stable release of XCode. Do you have steps that enable us to work out the compilation errors every time a new build is released?

**Comment by fespinoza** [comment]
I saw this related the lack of module stability of the zendesk SDK

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

basically they need to add the

```
BUILD_LIBRARY_FOR_DISTRIBUTION = YES;
```

setting to the project.

I sent an email to zendesk and they reply to me about asking contact people from my company and company credentials rather than appropriate answer for a technical problem

**Comment by 570262616** [comment]
> This sdk is a joke... Each time swift compiler is updated Zendesk SDK is not compiling... great job guys! 👌🏼🤔

yup, this sdk is a joke🤔

**Pull request merged**
