### PR TITLE
Remove unnecessary imports to solve reference cycle issue

### PR DESCRIPTION
**Pull request by linktoming**
ideally it should be fixed in the source code instead of in the public header. You may want to do that internally.

### CODE REVIEW

**Comment by tecknut** [comment]
@linktoming Thanks for pointing this out. This repo is just a place for us to host our binary, so merging this isn't something we will do. 

Can you instead create an issue for us to track and mark as solved with our next release? 

Thanks

**Comment by linktoming** [comment]
@tecknut it caused build error in our project using cocoapods. Manually adding the framework worked fine somehow.

**Comment by tecknut** [comment]
@linktoming To me that would suggest there is something up with how cocoapods creates the xcconfig files on install or update. Regardless this is something we can fix with the imports.

This happens because we have file templates for Xcode, and when we create a subclass from one of our own classes Xcode looks for the supper classes framework as the import. 

Thanks for opening issue, this will be fixed in our next release.

**Comment by linktoming** [comment]
Thanks 👍

**Pull request closed without merging**
